title: Python API Basics
description: Tutorial to create a simple API using Python and FastAPI
theme: just-the-docs

url: https://pschonev.github.io/python-api-basics

color_scheme: dark

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/pschonev/python-api-basics
